---
  - hosts: devmachine
    gather_facts: yes
    #remote_user: vagrant

    vars:
      locale: de_DE.UTF-8
      timezone: Europe/Berlin

    tasks:

#
# Update locale to germany
#
      - locale_gen:
          name: "{{ locale }}"
          state: present
        become: yes
      - name: set locale
        command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
        become: yes
      - name: set /etc/localtime
        file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
        become: yes
      - name: update tzdata
        command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
        become: yes
#
# Add repositories for special software
#

      - name: TOOLS | add terminator repo
        apt_repository: repo='ppa:gnome-terminator/nightly' state=present
        become: yes

      - name: TOOLS | Add Oracle Java Repository
        apt_repository: repo='ppa:webupd8team/java'
        become: yes

      - name: TOOLS | Add Sublime Repository
        apt_repository: repo='ppa:webupd8team/sublime-text-2'
        become: yes

      - name: TOOLS | Add Gradle Repository
        apt_repository: repo='ppa:cwchien/gradle'
        become: yes

      - name: TOOLS | Google Chrome ppa key installation
        apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub
        become: yes
      - name: TOOLS | Add Google Chrome Repository
        apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present
        become: yes

      - name: TOOLS | Virtualbox key installation
        apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
        become: yes
      - name: TOOLS | Add Virtualbox Repository
        apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian xenial contrib' state=present
        become: yes

      - name: TOOLS | Docker key installation
        apt_key: url=https://download.docker.com/linux/ubuntu/gpg
        become: yes
      - name: TOOLS | Add Docker Repository
        apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable' state=present update_cache=yes
        become: yes

#
# Installation of Ubuntu basic packages
#

      - name: SYSTEM | upgrade
        apt: update_cache=yes upgrade=full
        become: yes

      - name: SYSTEM | ubuntu-gnome-desktop
        apt: name=ubuntu-gnome-desktop state=latest
        become: yes

      - name: SYSTEM | language-pack-de
        apt: name=language-pack-de state=latest
        become: yes

      - name: SYSTEM | aptitude
        apt: name=aptitude state=latest
        become: yes

      - name: SYSTEM | joe
        apt: name=joe state=latest
        become: yes

      - name: SYSTEM | unzip
        apt: name=unzip state=latest
        become: yes

      - name: SYSTEM | pigz
        apt: name=pigz state=latest
        become: yes

      - name: SYSTEM | htop
        apt: name=htop state=latest
        become: yes

      - name: SYSTEM | synaptic
        apt: name=synaptic state=latest
        become: yes

      - name: SYSTEM | ant
        apt: name=ant state=latest
        become: yes

      - name: SYSTEM | maven
        apt: name=maven state=latest
        become: yes

      - name: SYSTEM | KeePass
        apt: name=keepass2 state=latest
        become: yes

      - name: SYSTEM | Krusader
        apt: name=krusader state=latest
        become: yes

      - name: SYSTEM | Double Commander
        apt: name=doublecmd-gtk state=latest
        become: yes

      - name: SYSTEM | Double Commander Plugins
        apt: name=doublecmd-plugins state=latest
        become: yes

      - name: SYSTEM | Gnome Commander
        apt: name=gnome-commander state=latest
        become: yes

      - name: SYSTEM | Midnight Commander
        apt: name=mc state=latest
        become: yes

      - name: SYSTEM | Indicator Multiload
        apt: name=indicator-multiload state=latest
        become: yes

      - name: SYSTEM | dkms
        apt: name=dkms state=latest
        become: yes

      - name: SYSTEM | apt-transport-https
        apt: name=apt-transport-https state=latest
        become: yes

      - name: SYSTEM | ca-certificates
        apt: name=ca-certificates state=latest
        become: yes

      - name: SYSTEM | curl
        apt: name=curl state=latest
        become: yes

      - name: SYSTEM | software-properties-common
        apt: name=software-properties-common state=latest
        become: yes

#
# Installation of extra packages
#
      - name: TOOLS | terminator installation
        apt: name=terminator state=latest
        become: yes

      - name: TOOLS | Google Chrome stable installation
        apt: name=google-chrome-stable state=latest
        become: yes

      - name: TOOLS | Install add-apt-repostory for Java 8
        apt: name=software-properties-common state=latest
        become: yes
      - name: TOOLS | Accept Java 8 Licence
        shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-8-licence-acceptance | /usr/bin/debconf-set-selections
        become: yes
        args:
          creates: /etc/oracle-java-8-licence-acceptance
      - name: TOOLS | Install Oracle Java 8
        apt: name={{item}} state=latest
        become: yes
        with_items:
          - oracle-java8-installer
          - ca-certificates
          - oracle-java8-set-default

      - name: TOOLS | Sublime Text installation
        apt: name=sublime-text state=latest
        become: yes

      - name: TOOLS | Gradle installation
        apt: name=gradle state=latest
        become: yes

      - name: TOOLS | Virtualbox 5.1 installation
        apt: name=virtualbox-5.1 state=latest
        become: yes

      - name: TOOLS | Virtualbox dkms installation
        apt: name=virtualbox-dkms state=latest
        become: yes

      - name: TOOLS | Virtualbox guest dkms installation
        apt: name=virtualbox-guest-dkms state=latest
        become: yes

      - name: TOOLS | Docker-CE installation
        apt: name=docker-ce state=latest
        become: yes

      - name: TOOLS | Download Slack
        get_url:
          url: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.6.3-amd64.deb
          dest: ~/slack-desktop-2.6.3-amd64.deb
          force: no
        become: yes

      - name: TOOLS | Slack installation
        apt: deb=~/slack-desktop-2.6.3-amd64.deb
        become: yes

      - name: TOOLS | Android Studio prepartions
        apt: name={{item}} state=latest
        become: yes
        with_items:
          - libc6:i386
          - libncurses5:i386
          - libstdc++6:i386
          - lib32z1
          - libbz2-1.0:i386

      - name: TOOLS | Create download folder
        file:
          path: ~/downloads
          state: directory

      - name: TOOLS | Download Android Studio
        get_url:
          url: https://dl.google.com/dl/android/studio/ide-zips/2.3.3.0/android-studio-ide-162.4069837-linux.zip
          dest: ~/downloads/android-studio-ide-162.4069837-linux.zip
          force: no

      - name: TOOLS | Android Studio installation
        unarchive:
          src: ~/downloads/android-studio-ide-162.4069837-linux.zip
          dest: ~/
          remote_src: yes
          creates: ~/android-studio

      - name: TOOLS | Download Vagrant
        get_url:
          url: https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.deb
          dest: ~/vagrant_1.9.7_x86_64.deb
          force: no
        become: yes

      - name: TOOLS | Vagrant installation
        apt: deb=~/vagrant_1.9.7_x86_64.deb
        become: yes

      - name: TOOLS | Download Vivaldi
        get_url:
          url: https://downloads.vivaldi.com/stable/vivaldi-stable_1.10.867.48-1_amd64.deb
          dest: ~/vivaldi-stable_1.10.867.48-1_amd64.deb
          force: no
        become: yes

      - name: TOOLS | Vivaldi installation
        apt: deb=~/vivaldi-stable_1.10.867.48-1_amd64.deb
        become: yes

      - name: TOOLS | Download Eclipse
        get_url:
          url: http://ftp.fau.de/eclipse/technology/epp/downloads/release/oxygen/R/eclipse-jee-oxygen-R-linux-gtk-x86_64.tar.gz
          dest: ~/downloads/eclipse-jee-oxygen-R-linux-gtk-x86_64.tar.gz
          force: no

      - name: TOOLS | Create Eclipse installation folder
        file:
          path: ~/eclipse/oxygen-4.7
          state: directory

      - name: TOOLS | Eclipse installation
        unarchive:
          src: ~/downloads/eclipse-jee-oxygen-R-linux-gtk-x86_64.tar.gz
          dest: ~/eclipse/oxygen-4.7
          remote_src: yes
          creates: ~/eclipse/oxygen-4.7/eclipse
